// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrf8k5luDYs9FPp0h1KxRozmnDK94vVyU',
    appId: '1:451675011531:web:750724cc9585a2045d5e4e',
    messagingSenderId: '451675011531',
    projectId: 'growblic-authenticator',
    authDomain: 'growblic-authenticator.firebaseapp.com',
    storageBucket: 'growblic-authenticator.firebasestorage.app',
    measurementId: 'G-TSMHN8JY2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNiSku0WMcZjTLNjZI3CH_XsZ6oC_gwRs',
    appId: '1:451675011531:android:a4587544a87a59775d5e4e',
    messagingSenderId: '451675011531',
    projectId: 'growblic-authenticator',
    storageBucket: 'growblic-authenticator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr2LOLEPKcPOzr76oM_locUquaH8X0XDk',
    appId: '1:451675011531:ios:1e8965bd488c29845d5e4e',
    messagingSenderId: '451675011531',
    projectId: 'growblic-authenticator',
    storageBucket: 'growblic-authenticator.firebasestorage.app',
    iosClientId: '451675011531-03vta15squgcas2mqe15al5ov3jo1uak.apps.googleusercontent.com',
    iosBundleId: 'com.browblic.authenticator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr2LOLEPKcPOzr76oM_locUquaH8X0XDk',
    appId: '1:451675011531:ios:1e8965bd488c29845d5e4e',
    messagingSenderId: '451675011531',
    projectId: 'growblic-authenticator',
    storageBucket: 'growblic-authenticator.firebasestorage.app',
    iosClientId: '451675011531-03vta15squgcas2mqe15al5ov3jo1uak.apps.googleusercontent.com',
    iosBundleId: 'com.browblic.authenticator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrf8k5luDYs9FPp0h1KxRozmnDK94vVyU',
    appId: '1:451675011531:web:a75b4372b0d86e8e5d5e4e',
    messagingSenderId: '451675011531',
    projectId: 'growblic-authenticator',
    authDomain: 'growblic-authenticator.firebaseapp.com',
    storageBucket: 'growblic-authenticator.firebasestorage.app',
    measurementId: 'G-B94F7C64DF',
  );
}
